# Generated by Django 4.2 on 2024-02-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_movietype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='movietype',
            field=models.CharField(default='Action', max_length=30),
        ),
    ]
